import { DomDebugFlag } from './common';
import { SuiNavigation, scrollHandler, debugFlag } from '../render/sui/configuration';
import { Ref } from 'vue';
export declare class SuiNavigationDom implements SuiNavigation {
    static _instance: SuiNavigationDom;
    static get instance(): SuiNavigationDom;
    _displayMode: Ref<string>;
    crashUrl: string;
    scrollHandlers: scrollHandler[];
    _outerContainer?: HTMLElement;
    _scrollContainer?: HTMLElement;
    _scoreContainer?: HTMLElement;
    debugFlags: DomDebugFlag[];
    initialized: boolean;
    showSplash: Ref<boolean>;
    splashTimer: Ref<number>;
    showHelpDialog: Ref<boolean>;
    progressPercentValue: Ref<number>;
    showAttributeDialog: Ref<boolean>;
    crashReport: Ref<string>;
    showCrashReport: Ref<boolean>;
    displayExceptionDialog(message: string): void;
    showProgressModal(label: string): void;
    hideProgressModal(): void;
    setProgress(percent: number): void;
    showHelpModal(): void;
    isInitialized(): boolean;
    createDebugFlags(): void;
    get displayMode(): string;
    set displayMode(value: string);
    get outerContainer(): HTMLElement | undefined;
    set outerContainer(value: HTMLElement | undefined);
    get scrollContainer(): HTMLElement;
    get scoreContainer(): HTMLElement;
    constructor(uiDomContainer?: HTMLElement);
    initialize(): void;
    showDebugString(flag: debugFlag, htmlString: string): void;
    get scrollable(): string;
    pushScrollHandler(handler: scrollHandler): void;
    popScrollHandler(): scrollHandler | undefined;
    showSplashModal(timeout?: number): void;
    showDialogModal(): void;
    hideDialogModal(): void;
}
